### ISSUE TITLE
Parallel calculator example doesn't yield consistent result as single calculator

### ISSUE THREAD

**Issue by chiahaoliu** [diffpy/diffpy.srreal#8]
I was trying the parallel PDF calculator from the ``parallelPDF.py`` included in example directory. The parallelizing was successful but the result from parallel calculator seems to be the different from single-pass one.

I only edited the plotting part of ``parallelPDF.py`` as following so it shows the legend:

````
....
plot(r0, g0, label='single')
plot(r1, g1, label='parallel')
plot(r0, gd - 3, label='diff')
plt.legend()
show()
````
and the result obtained is:

![srreal_parallel_cal_error](https://user-images.githubusercontent.com/15218640/27598639-1d77971a-5b34-11e7-9577-373ed0ec3ba9.png)

package info:
````
diffpy-cmi                2.0.2                         0    diffpy
diffpy.pdffit2            1.1                      py27_0    diffpy
diffpy.srfit              1.2                      py27_0    diffpy
diffpy.srreal             1.1.3                    py27_0    diffpy
diffpy.structure          1.3.4                    py27_0    diffpy
diffpy.utils              1.2.1                    py27_0    diffpy
````

Any thought? Thanks :)

**Comment by pavoljuhas** [comment]
Thank you for reporting this.  This bug showed up after the default `PDFCalculator.evaluatortype` was changed to `OPTIMIZED`; in this mode PDF contributions are updated only for the changed atoms.  This does not play well with parallel calculation - the parallel workers use a deep copy of the original calculator object, which in the example is synced with the menthol structure.  Hence on the second call they all return zero as their partial result and the combined PDF is zero as well, i.e., just the linear background.

The immediate workaround is to pass `evaluatortype="BASIC"` when creating a calculator instance, e.g., add that to the [cfg dictionary](https://github.com/diffpy/diffpy.srreal/blob/211f209fb3e9f1fcbd3b37aa986139e1719dc8d7/examples/parallelPDF.py#L46-L49).

Thinking of it, the current PARALLEL+OPTIMIZED evaluation is broken.  Parallel workers receive a copy of the template calculator with the last result cached, but that is a result for a full PDF and not its 1/NCPU parallel share.  Thus they cannot even correctly update the partial result (for say a single atom moved), because the initial value is not right.  The current implementation in [parallel.py](https://github.com/diffpy/diffpy.srreal/blob/211f209fb3e9f1fcbd3b37aa986139e1719dc8d7/src/diffpy/srreal/parallel.py#L85-L92) runs each call with a new instance of the calculator object on worker side (it is pickled and copied to worker at the parallel map call) so there is no way for the workers to cache a correct partial result.  To get it right, the master process should keep proxy handles to the calculator objects living on parallel workers and reuse them in subsequent evaluations.  This is possible with the *multiprocessing* module, but I am not convinced the benefit of having PARALLEL+OPTIMIZED procedure fixed is worth the effort.  As it is, the parallel calculation works OK with BASIC evaluator, which always computes the PDF from scratch.

As a stopgap solution I suggest to
- [ ] adjust the parallelPDF.py example to use the "BASIC" evaluator.
- [ ] require BASIC evaluator for any calculators pased to the `parallel.createParallelCalculator` factory.

@sbillinge, @chiahaoliu, @CJ-Wright - any comments?

**Comment by pavoljuhas** [comment]
> ~~require BASIC evaluator for any calculators pased to the parallel.createParallelCalculator factory.~~

There are less ripple effects (in srfit, for example) if factory just reset the evaluatortype to BASIC.

> adjust the parallelPDF.py example to use the "BASIC" evaluator.

No need for any adjustments with factory-reset evaluatortype.
